// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0AG8WVmJ4Glp50GNDVpg5dR6LD6GB3rM',
    appId: '1:143675706890:web:892c4aab66e205d99b19f3',
    messagingSenderId: '143675706890',
    projectId: 'chat-app-60422',
    authDomain: 'chat-app-60422.firebaseapp.com',
    storageBucket: 'chat-app-60422.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvp31j1MzgDfvikXA6m6LwhY68DBe6kdo',
    appId: '1:143675706890:android:75d00843e4e737789b19f3',
    messagingSenderId: '143675706890',
    projectId: 'chat-app-60422',
    storageBucket: 'chat-app-60422.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUZejLqnf_MKP8fIiHF-qSU5eNfc9RPeU',
    appId: '1:143675706890:ios:f93da94db704ccc89b19f3',
    messagingSenderId: '143675706890',
    projectId: 'chat-app-60422',
    storageBucket: 'chat-app-60422.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUZejLqnf_MKP8fIiHF-qSU5eNfc9RPeU',
    appId: '1:143675706890:ios:f93da94db704ccc89b19f3',
    messagingSenderId: '143675706890',
    projectId: 'chat-app-60422',
    storageBucket: 'chat-app-60422.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0AG8WVmJ4Glp50GNDVpg5dR6LD6GB3rM',
    appId: '1:143675706890:web:71d34276f547f77f9b19f3',
    messagingSenderId: '143675706890',
    projectId: 'chat-app-60422',
    authDomain: 'chat-app-60422.firebaseapp.com',
    storageBucket: 'chat-app-60422.appspot.com',
  );

}